### ISSUE TITLE
Payment flow in tnbCrow

### ISSUE THREAD

**Issue by hussu010** [tnbCrow/Backend#129]
- tnbCrow users will have a unique memo associated with their account.
- Users will send coins to the tnbCrow wallet address with their memo.
- User will click the **Scan Transaction** button. The BE will scan the chain and update the user's balance accordingly.

#### What if the users send coins without a memo?
We will refund the coins excluding the transaction fees.

**Comment by zinoadidi** [comment]
> * tnbCrow users will have a unique memo associated with their account.
> * Users will send coins to the tnbCrow wallet address with their memo.
> * User will click the **Scan Transaction** button. The BE will scan the chain and update the user's balance accordingly.
> 
> #### What if the users send coins without a memo?
> We will refund the coins excluding the transaction fees.

let the ones who sent without memo file a refund request for making such horrible mistakes :)
