### ISSUE TITLE
User Dashboard

### ISSUE THREAD

**Issue by dhakal0kushal** [tnbCrow/Backend#49]
- Recent trades completed by the user (will show the reputation earned, amount of coins, rate, role)
- Total amount of coins traded
- Graph (coins traded, change of rate per unit time
- User Profile Picture
- Total reputation
- Bio of the user? It's not social media platform but why not lol
- Total coins loaded(Private to User)

**Comment by denistsoi** [comment]
> - Total coins loaded(Private to User)

I assume this is loaded in escrow right? 

> - User Profile Picture
> - Bio of the user? It's not social media platform but why not lol
Nice to have - it's fun but non-essential (can always converse on discord/slack to confirm trade)

**Comment by dhakal0kushal** [comment]
@denistsoi exactly.
I wrote down the logic for coins loaded in tnbCrow. What do you think about this:
#### Role - Seller
- User will load the coins into tnbCrow wallet. We will scan the chain with the memo and update the balance of the user.
- When the user is creating a trade request, they will need to have `X` coins loaded into their account before creating a trading post.
- Once they create a trading post, the balance of the user is deducted so as to stop them from creating another trading post with no coins into the wallet.
- If they cancel or delete the trading post, the balance gets added to their account.
- If the trade is completed, we'll send coins to the buyer's primary wallet address.
#### Role - Buyer
- The user will create a trade request with the number of coins that they want.
- The seller will need to have `X` coins loaded into their account before creating a trade request.
- Once they create a trade request, the balance of the user is deducted so as to stop them from creating another trading post with no coins into the wallet.
- If the buyer cancels or deletes the trading post, the balance gets added to the seller's account.
- If the trade is completed, we'll send coins to the buyer's primary wallet address.

**Comment by dhakal0kushal** [comment]
https://github.com/tnbCrow/Design/issues/6
