### ISSUE TITLE
Memo? Do we need to wait for it?

### ISSUE THREAD

**Issue by dhakal0kushal** [tnbCrow/Backend#52]
so the idea is:

- if you want to add an account number, you send eg 1tnbc to the account bucky burnt the other coins at
this is a one-time activity
- you send us the same info as above; we verify you
- in future you send money to us, you don't need to do this anymore
- so that provides extra checks for shady people trying to rip others of their coins
- this burning step can then be replaced with the memo when it's ready

C.R: @zinoadidi

**Comment by zinoadidi** [comment]
Information from here is sufficient
![image (4)](https://user-images.githubusercontent.com/30411401/111591639-660ce300-87d0-11eb-90ac-7672c8f2aac8.png)

At the moment the only edge case we have is someone else trying to get another person to transfer coins to us >> that's if we use our own set of account numbers for receiving payments.

This edge case also exist with the current escrow system.

We can provide in addition to everything the current human escrow provides, accuracy, transparency so i believe the idea should not wait on the memo.

The steps provided above should be sufficient for alerting the possible victims that something is off is someone randomly asks them to burn their coins for reasons that don't add up

**Comment by dhakal0kushal** [comment]
creating a lock-in account number with the time duration
this way they will need to send the coins to the verification account in that duration
if they fail to do so, we will release the account number that way another person, if it's their account, can verify it
once verified, every coin sent to our wallet from that account number will be added to their account.
C.R: @zinoadidi

**Comment by dhakal0kushal** [comment]
### Summary:
Before we get a memo update from the chain, we can use this alternative method to verify that a wallet belongs to a particular user and use it to update the balance to their tnbCrow account.
#### How?
- Create an endpoint that will be responsible for verifying the account number.
#### Steps:
- User will add the wallet address to tnbCrow and send it for verification. 
- They will then send 1 coin to #0000000000000... using the wallet that they are verifying. 
- They will click scan the chain button. If there is a transaction made into #0000000.. we will associate that wallet address to their account and every time they make a transition to tnbCrow wallet using that account, we will update their account balance.
- We will impose a lock into account number that way, if someone is verifying an account number, another person cannot verify it. The lock duration will be five minutes.  Also, one account number can be associated with only one tnbCrow account.

**Comment by dhakal0kushal** [comment]
Since we already have memo update in chain, we wont need to worry about the alternative of memo anymore :D
